# Generated by Django 5.2.17 on 2026-08-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='ISO 4217 code, e.g., USD, INR', max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('exchange_rate_to_base', models.DecimalField(decimal_places=6, default=1.0, help_text='Exchange rate to the base system currency', max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
